### PR TITLE
fix: Collapse nav bar to menu for small screens

### LINKED ISSUE #54: Fix header styling on narrow/mobile displays
Header is messed up when the screen width is small.

### PR DESCRIPTION
**Pull request by jayden-chan**
Closes #54 

I changed the nav bar to a hamburger menu when the screen size is narrow. I think it looks pretty good, we may even want to just have it like this for all screen sizes. Let me know what you guys think

image

### CODE REVIEW

**Review by nicudy — APPROVED** [review]

File: src/components/Nav.tsx [hunk 1]
```diff
@@ -107,21 +120,80 @@ export const NavHeader = () => {
...
+            </Menu>
+          </>
+        ) : (
+          <>
+            <NavLink to="/" desc="Home" />
+            <NavLink to="/profileManagement" desc="Profile Management" />
+            <NavLink to="/schedule" desc="View Schedules" />
+            <NavLink to="/survey" desc="Preferences Survey" />
+            <NavLink to="/surveyresults" desc="Survey Results" />
+            {isAdmin && (
```
Comment (cbuchko) [inline src/components/Nav.tsx:217]: Is this the correct separation for admin/non-admin content? I thought the regular professors were only able to submit their survey and shouldn't be able to access routes like View Schedules and Survey Results.

**Review by cbuchko — COMMENTED** [review]
Looks great, just one comment. In regards to having the hamburger at all screen sizes, I personally like having the full nav bar if the screen supports it

File: src/components/Nav.tsx (hunk 1 above)
Comment (cbuchko) [reply src/components/Nav.tsx:217]: oh you know what, nvm, looking at Nicole's PR and she implemented the separation in that

**Review by cbuchko — APPROVED** [review]
